---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/users":
    get:
      summary: Retrieves all users
      tags:
      - Users
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    email:
                      type: string
                  required:
                  - id
                  - name
                  - email
servers:
- url: http://{localHost}
  variables:
    localHost:
      default: localhost:3000
